elasticsearch:
  image: jonbrouse/elk:elasticsearch
  extends:
    file: docker-compose-common.yml
    service: elasticsearch
logstash:
  image: jonbrouse/elk:logstash
  extends:
    file: docker-compose-common.yml
    service: logstash
  links:
    - elasticsearch
kibana:
  image: jonbrouse/elk:kibana
  extends:
    file: docker-compose-common.yml
    service: kibana
  links:
    - elasticsearch
fluentd:
  image: jonbrouse/elk:fluentd
  extends:
    file: docker-compose-common.yml
    service: fluentd
  links:
    - logstash
