elasticsearch:
  image: jonbrouse/elk:elasticsearch
  extends:
    file: docker-compose-common.yml
    service: elasticsearch
  volumes:
    - elasticsearch/volumes/esdata/:/opt/elasticsearch/data
logstash:
  image: jonbrouse/elk:logstash
  extends:
    file: docker-compose-common.yml
    service: logstash
  links:
    - elasticsearch
kibana:
  image: jonbrouse/elk:kibana
  extends:
    file: docker-compose-common.yml
    service: kibana
  links:
    - elasticsearch
nginx:
  build: nginx
  extends:
    file: docker-compose-common.yml
    service: nginx
  links:
    - kibana
