elasticsearch:
  extends:
    file: docker-compose-common.yml
    service: elasticsearch
  build: elasticsearch
logstash:
  extends:
    file: docker-compose-common.yml
    service: logstash
  build: logstash
  links:
    - elasticsearch
kibana:
  extends:
    file: docker-compose-common.yml
    service: kibana
  build: kibana
  links:
    - elasticsearch
fluentd:
  extends:
    file: docker-compose-common.yml
    service: fluentd
  build: fluentd
  links:
    - logstash
