elasticsearch:
  build: elasticsearch
  extends:
    file: docker-compose-common.yml
    service: elasticsearch
  volumes:
    - elasticsearch/volumes/esdata/:/opt/elasticsearch/data
logstash:
  build: logstash
  extends:
    file: docker-compose-common.yml
    service: logstash
  links:
    - elasticsearch
kibana:
  build: kibana
  extends:
    file: docker-compose-common.yml
    service: kibana
  links:
    - elasticsearch
nginx:
  build: nginx
  extends:
    file: docker-compose-common.yml
    service: nginx
  links:
    - kibana
