elasticsearch:
  extends:
    file: docker-compose-common.yml
    service: elasticsearch
  build: elasticsearch
logstash:
  extends:
    file: docker-compose-common.yml
    service: logstash
  build: logstash
kibana:
  extends:
    file: docker-compose-common.yml
    service: kibana
  build: kibana
